"""add user_id to connectors

Revision ID: 2adfc41bd2b6
Revises: bc1efcca1adc
Create Date: 2026-09-05 16:24:33.228548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adfc41bd2b6'
down_revision: Union[str, Sequence[str], None] = 'bc1efcca1adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_user_id'), 'connectors', ['user_id'], unique=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'profile_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_connectors_user_id'), table_name='connectors')
    op.drop_table('connectors')
    # ### end Alembic commands ###
