[project]
name = "user-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rajeshrc12", email = "rajesh.charhajari@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.2",
    "boto3>=1.43.89",
    "fastapi>=0.141.1",
    "google-auth>=2.57.1",
    "psycopg[binary]>=3.3.5",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
user-service = "user_service:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
