[project]
name = "user-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rajeshrc12", email = "rajesh.charhajari@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
user-service = "user_service:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
